# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
version: '3'
services:
  postgres:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/postgres:${PRIMERO_TAG:-latest}-pg${PRIMERO_POSTGRES_VERSION:-15}'
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    env_file:
      - docker/defaults.env
      - docker/local.env
    restart: always
    profiles:
      - db
  application:
    profiles:
      - app
    depends_on:
      solr:
        condition: 'service_started'
        required: true
      postgres:
        condition: 'service_started'
        required: false
  worker:
    profiles:
      - app
    depends_on:
      solr:
        condition: 'service_started'
        required: true
      postgres:
        condition: 'service_started'
        required: false
