# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
version: '3'
services:
  nginx:
    image: '${PRIMERO_IMAGE_REPOSITORY:-primeroims}/nginx:${PRIMERO_TAG:-latest}'
    ports:
      - "80:80"
      - "443:443"
    profiles:
      - app
    volumes:
      - 'certbot_certificates:/etc/letsencrypt'
      - 'certbot_challenges:/usr/share/nginx/html/.well-known/acme-challenge'
      - public:/srv/primero/application/public
      - selfsigned_certs:/certs
      - /srv/external-certs:/external-certs
    env_file:
      - docker/defaults.env
      - docker/local.env
    depends_on:
      - application
    restart: always
  application:
    env_file:
      - docker/defaults.env
      - docker/local.env
  solr:
    profiles:
      - solr
    env_file:
      - docker/defaults.env
      - docker/local.env
  worker:
    volumes:
      - public:/srv/primero/application/public
    env_file:
      - docker/defaults.env
      - docker/local.env

