# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
- name: 'prune dangling Docker images'
  command: |
    docker image prune -f
  tags:
  - 'prune'

- name: 'prune dangling Docker volumes'
  command: |
    docker volume prune -f
  tags:
  - 'prune'
