# Copyright (c) 2014 - 2023 UNICEF. All rights reserved.

---
- hosts: 'all:localhost'
  environment:
    PATH: '{{ ansible_env.PATH }}:/opt/docker/bin/'
  roles:
  - 'manage-users'
  - 'application-primero'
  - 'prune'
